### PR TITLE
👽🤔🌽

### PR DESCRIPTION
**Pull request by JuhQ**
t̷̡̫̤̺͎̖͎̳̤̳̞̥̟̙̞̘͉͙͔́̉̈̄̑̽ͫ́̊̋̾͑̚͟͞͡ͅḧ̵̶́̍̐́ͪ̚͘҉͇̟͖͚̙̰̲͉̮͚̺͔e̴̴̢̢͚̳̞͙̅ͥ̄ͧ͡ ̵̮͎̮̫̬̳̫̑͒̊́̽̇̔̄͒̈ͦ͊̏̕̕ḑ̸͇͚͚̮̭̼̖̪̗̥͙͇̖̲̅̂ͯ͑̑̔͐̿̄̒̉̽̽ͩ͡a̶͆͑ͧͧͩͣͨ̍ͩͮͮ͆ͯ́͏͉̹͔͙͉͓̜̖̦̱̱͖r̉ͦ͌ͫͧ͗͆̄ͣ̈́ͫͫ̈́̋͞҉̺̯̱̠̮k̹̥̲̲͇̭̺̲̜̙̣͍̩̩͂͑̐ͪͥ̑̀̂́̀ǹ̵̡͍̫̪̭̳͕͓͓̦̖͙̤̮̯̫̝͚́ͬ̋̿̈́̓ͪ̆̊̈̄͆̿͌́͝ͅe̷̢̤͖̥͎̻̜͙̣̬̞̻͎̣͚̹̻͚̯ͧͤ̊ͤͧ͑̂̐ͥͯ͜͞sͩ́̍̿̒͆ͥ̈́͐̊̑̄̀̉̅ͯ̀̕҉̲̜͎̖̮̖̖̪̦̪̠͖̀ͅś̶̭͈̻͉͍͇̯ͪͪ̉̌̃ͯ͌ͮ̅͋̆̋̾͐ͧ͌̀͘͡ͅ ̨̡̼̱̲͙̰͒͂͑͒ͣ͌̌͒̋̒͞c̵̢͈͈̜̜͍̬̳̟̜͉͖̮̘͕̺͈ͭͩ̍͂̈͒̋̔̃̽ͣ͘͡͝ͅo̶̢̤͓̫̦̘̖̱͍̒ͯ̓̔ͭͥ̄̂ͬ̐͗̉̓ͧ͞ͅņ̸̯̯̰̦̹̘̬̼̗̌͑́̽̀͞s̨͈̞̱͎̥̝̠͇̳̞͓̠͂ͧ͌̽̍̉ͩ͌̂ͭ̏̿̀̓ͪ̓͒ͮͅu͖̲̫̪͕̞͕͎̦̽̾ͥ̍ͪ̽́͘͠͠ͅm̸̡̢͎͙̮̹̟̟͌͊̏ͨ͌ͦ̄ͤͦ̈͜͝ͅͅę̷̨̮̫͚̼̆̓̄ͭͥ̋͐̾͞͞s̉͗ͫ̏̊͊ͥ̓͑͛ͮ̊̀̉͂̒͜҉̶̩͈̘͔͍̤͎̬͜ ̸̶̷̢̮̖̯͇̙̦̞̻͓̹̤͉̿̌̅͐ͣͩ̿ͫ̌̍̀̈́͆̚̚ͅm̷̵̧̞̹͓̖̖̗̰̤̼͚͚̘ͤ̎ͦ̾̽̐͢ͅͅͅe̷̥̺̭̰̤̠̞̩̯̮̘̓̈̔͋ͪ̓̓́͢͟͡ͅͅͅ

### CODE REVIEW

**Comment by Jakousa** [comment]
Does not work if shibbolethHeaders is undefined. plz fix

**Comment by JuhQ** [comment]
lol out of scope of pr

**Comment by JuhQ** [comment]
.
.
ẃ̛͔̼̱̘̘̞̯̩̎͒͟͡͞͞͝h̶̨̧͓̺̘̺̤̭̓̒̽̈́͌̅ͅỳ̨̬̼͎̦̤̲̓͒̎͌͟ͅ h̸̢͎̮̖̹̹̣̞̙͍̊̀̏̔͌͐̒͞a̵̛͍̘̯̫̼̎͂̋̾͗̎̿̽ș̸͍̘̑͐͛̍͐̅͟͟͠ṫ̲̠̺̰͉̮͑̃̔̑ t̼̺̥̱͙͚̑̒̄̅͆̉̄͂̂̅͢ͅh̡̯̣̻͙̃̋̓̐̒͐́͋͜͝͡o̴̧̡̡͇͍͔̔̍̀̎̕͠u̧̢̲̙͕͉̭̣̙̓̈́̔̀̓̃̈̾ f̴͓͖̘͉̟̤̈̓͐͌̆̂̕͘͝͞o̶̙̬͖͐̊͊̓̓͘̚͜͟ṟ̴͓̣̭̃̔̉́̄̽̂͂̿͜͝ś̡̟͉̝͈͍͙̤͐̽͋̊͑͢ͅa͈͉̣̫̼͍͊͊̑̿̈́͌̚͜͞ǩ̷̻̟̲̘̼͉̹͓̉̎̐̕̕͟͟e̵̡̢̯͓͍͎̙̮͛̊̅͛̒n̢̨̛̛̥̘̳̼̘̐͆̿͌̂͟͞ m̴̲͉̦̦̱͙̃̇̓̾̐̚͝e͚̻̫͍̦͖̤͑͐͆̀͛?̡̮̠̖̭͆͒̊̊̿̅͘̚̚
.
.

**Comment by Jakousa** [comment]
```js
  const newHeaders = shibbolethHeaders
    .filter(header => req.headers[header])
    .reduce((acc, header) => ({
      ...acc,
      [header]: Buffer.from(req.headers[header], 'latin1').toString('utf8')
    }), req.headers)
```

newHeaders already contains all of the headers as reduce starts from req.headers. This is probably redundant

```
  req.headers = {
    ...req.headers, <---
    ...newHeaders
  }
```

Consider replacing with ` req.headers = newHeaders `

**Comment by Jakousa** [comment]
I'll accept it next week for hacktoberfest.

**Comment by Jakousa** [comment]
Plz fix conflicts

**Pull request closed without merging**
